name: CustomEvents
author: Flowsqy
version: "${project.version}"
main: fr.flowsqy.customevents.CustomEventsPlugin
api-version: "1.15"
permissions:
  customevents.command:
    description: "CustomEvents command base permission"
    default: op
  customevents.command.help:
    description: "Grant the permission to see help message"
    default: op
    children:
      customevents.command: true
  customevents.command.start:
    description: "Grant the permission to force an event"
    default: op
    children:
      customevents.command: true
  customevents.command.info:
    description: "Grant the permission to see an event"
    default: op
    children:
      customevents.command: true
  customevents.command.reload:
    description: "Grant the permission to reload event configurations"
    default: op
    children:
      customevents.command: true
  customevents.command.check:
    description: "Grant the permission to check an event"
    default: op
    children:
      customevents.command: true
  customevents.command.*:
    description: "Grant all the command permissions"
    default: op
    children:
      customevents.command.help: true
      customevents.command.start: true
      customevents.command.info: true
      customevents.command.reload: true
      customevents.command.check: true
commands:
  customevents:
    description: "CustomEvents root command"
    permission: customevents.command
    usage: "/<command> <sub-command>"
    aliases:
      - events
      - cevents
      - ce